export const INTEGRATION_TYPES = {
  SHOPIFY: "SHOPIFY",
  MAILGUN: "MAIL_GUN",
  SENDGRID: "SEND_GRID",
  GMAIL: "GMAIL",
};

export const INTEGRATION_CATEGORY = {
  ECOMMERCE: "ECOMMERCE",
  MAIL_SERVICE: "MAIL_SERVICE",
};
