pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Aswin2667/shopify-partner-crm.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                    script {
                        sh 'docker build -t shopcrm-client .'
                    }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Deployment to Heroku was successful!'
        }
        failure {
            echo 'Deployment to Heroku failed.'
        }
    }
}
